accounts/urls.py
from django.urls import path, re_path
from . import views

from accounts.badge_views import Pioneer, Explorer, Adventurer



app_name="accounts"

urlpatterns = [
	path('', views.home, name="home"), 
	#account authenticating
 	path('logout/', views.logout_view, {'template_name': 'accounts/logout.html'}, name='logout'),
	#profile details
	path('profile/', views.view_profile, name='view_profile'),
	path('profile/edit/', views.edit_profile, name="edit_profile"),
	#password details
	path('profile/password/', views.change_password, 
		name="change_password"),

	#badges
	path('pioneer-progress/', Pioneer.as_view(), name='pioneer_progress'),
	path('explorer-progress/', Explorer.as_view(), name='explorer_progress'),
	path('adventurer-progress/', Adventurer.as_view(), name='adventurer_progress'),

	] 

home/urls.py
from django.urls import include, path
from django.contrib import admin

from home.views import (
	WelcomeView, 
	PricingView, 
	Contact, 
#	SubscribeView, 
#	SuccessView,
#	index,
	ChargeView,

	)


app_name='home_page'

urlpatterns = [
	path('', WelcomeView.as_view(), name='home'),
	path('pricing/', PricingView.as_view(), name='pricing'),
#	path('pricing/payment', include('djstripe.urls', namespace="djstripe")),


#	path('pricing/checkout', CheckOutView.as_view(), name='checkout'),
	path('contact-us/', Contact.as_view(), name='contact'),
#	path('thank_you/', SuccessView.as_view(), name='thank_you'),
#	path('subscribe/', SubscribeView.as_view(), name='subscribe'),

	path('pricing/paid/', ChargeView.as_view(), name='paid'),
]

record_book/urls.py
from django.urls import path, re_path
from login import views
from record_book.views import Pioneer



app_name="login"

urlpatterns = [
	path('pioneer', Pioneer.as_view(), name='Pioneer_intro'),
	] 

scouts/urls.py
from django.urls import include, path
from django.contrib import admin
from scouts.views import Login_Error_redirect
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.conf import settings
from django.conf.urls.static import static

main_urls = [
path('account/', include('accounts.urls', namespace='accounts'))
    
]


urlpatterns = [
#    path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('leaders/scout_info/', admin.site.urls),
    path('leaders/', include('leaders.urls', namespace='leaders')),

    path('account/', Login_Error_redirect.as_view(), name="accounts_redirect"),
    path('', include('home.urls', namespace='home_page')),
    path('login/',  include('login.urls', namespace='login')),
    path('record_book/', include('record_book.urls', namespace='record_book')),
    path('<slug:slug>/', include(main_urls))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

record_book/models.py
from django.db import models

# Create your models here.

record_book/views.py
from django.views.generic import TemplateView
from django.shortcuts import render, redirect



from django.contrib.auth.models import User

class Pioneer(TemplateView):
	template_name = 'record_book/pioneer.html'

	def get(self, request):
		user = request.user
		args = {'user': user}
		return render(request, self.template_name, args)
	

record_book/templates/record_book/pioneer.html
{% extends 'base.html' %}

{% block head %}
<title>Pioneer Badge</title>
<!-- <link rel="stylesheet" href="css/pioneer.css"> -->
{% endblock %}

{% block body %}
<div class="container">
	<h1 style= "color: red;">Pioneer</h1>
	<h3>What is it?</h3>
	<p>During your journey through scouting you will discover there are 3 main sections and goals you need to aim for. The first being the Pioneer Badge. The pioneer target Badges are design to be get you to experience what scouting is all about; going new places,  doing practical and adventurous activities as well as teaching you the vital scouting skills.</p> 
<br>
	
	<h3>Requirements</h3>
	<ul>
		<li><a href="#">Campcraft</a></li>
		<li><a href="#">Citizenship</a></li>
	</ul>
	<p>The completion of at least 1 of the following:</p>
	<ul>
		<li><a href="#">Air Activities</a></li>
		<li><a href="#">Construction</a></li>
		<li><a href="#">Environment</a></li>
		<li><a href="#">Water Activities</a></li>
		<li><a href="#">Water Safety</a></li>
	</ul>
	<h4>Completing the above gets you the pioneer badge</h4>
	<h3>If you wish to earn the red chord, you need:</h3>
	<ul>
		<li><a href="#">Patrol Activity</a></li>
		<li><a href="#dff">2 Profiency Badges</a></li>
	</ul>


	<h3>Red cord: {{ user.userprofile.red_cord }}</h3>
	<br>
	<a class="btn btn-outline-secondary" href="{% url 'accounts:view_profile' %}" role="button">Back</a>
</div>
<br>
<br>
{% endblock %}