home/urls.py
from django.urls import include, path
from django.contrib import admin

from home.views import (
	WelcomeView, 
	PricingView, 
	Contact, 
#	SubscribeView, 
#	SuccessView,
#	index,
	ChargeView,

	)


app_name='home_page'

urlpatterns = [
	path('', WelcomeView.as_view(), name='home'),
	path('pricing/', PricingView.as_view(), name='pricing'),
#	path('pricing/payment', include('djstripe.urls', namespace="djstripe")),


#	path('pricing/checkout', CheckOutView.as_view(), name='checkout'),
	path('contact-us/', Contact.as_view(), name='contact'),
#	path('thank_you/', SuccessView.as_view(), name='thank_you'),
#	path('subscribe/', SubscribeView.as_view(), name='subscribe'),

	path('pricing/paid/', ChargeView.as_view(), name='paid'),
]

login/urls.py
from django.urls import path, re_path, reverse_lazy
from login import views
from login.views import Login, Register

from django.contrib.auth.views import (
	LoginView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, 
	PasswordResetCompleteView
	)
from django.shortcuts import redirect


app_name="login"

urlpatterns = [
	path('', Login.as_view(), name='login'),
	#setting up accounts, to look over later
	path('register', Register.as_view(), name='register'),
	path('reset-password/', PasswordResetView.as_view(
		template_name= 'login/reset_password.html', 
		success_url= 'done/', 
		email_template_name= 'login/reset_password_email.html',
		), name='reset_password'),

	path('reset-password/done/', PasswordResetDoneView.as_view( 
		template_name= 'login/reset_password_done.html'), name='password_reset_done'),
	
	re_path(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', 
		PasswordResetConfirmView.as_view(
			template_name= 'login/reset_password_confirm.html', 
			success_url= reverse_lazy('login:password_reset_complete')),
			
		name='password_reset_confirm'),

	path('reset-password/complete/', PasswordResetCompleteView.as_view( 
		template_name= 'login/reset_password_complete.html'),
	 name="password_reset_complete"),

	] 

scouts/urls.py
from django.urls import include, path
from django.contrib import admin
from scouts.views import Login_Error_redirect
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.conf import settings
from django.conf.urls.static import static

main_urls = [
path('account/', include('accounts.urls', namespace='accounts'))
    
]


urlpatterns = [
#    path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('leaders/scout_info/', admin.site.urls),
    path('leaders/', include('leaders.urls', namespace='leaders')),

    path('account/', Login_Error_redirect.as_view(), name="accounts_redirect"),
    path('', include('home.urls', namespace='home_page')),
    path('login/',  include('login.urls', namespace='login')),
    path('record_book/', include('record_book.urls', namespace='record_book')),
    path('<slug:slug>/', include(main_urls))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

login/models.py
#in case having the troop details within the userprofile does not work

from django.db import models
from django.contrib.auth.models import User

from login.groups import Groups

# Create your models here.

class ScoutGroupManager(models.Manager):
	def get_queryset(self):
		return super(Scout_Group, self).get_queryset()

class ScoutGroup(models.Model):

	Group_Choice = Groups.Scout_Groups()
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	Troop = models.SlugField(max_length=27, choices=Group_Choice, default='None', blank=False)

login/views.py
from django.views.generic import TemplateView
from django.shortcuts import render, redirect

from django.contrib.auth.views import LoginView

from accounts.forms import RegistrationForm

from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User, Group
from accounts.models import UserProfile, UserProfileManager
from login.userprofile_finder import UserProfileGetter 
# Create your views here.






		
class Login(TemplateView):
	template_name = 'login/login.html'


	def get(self, request):
		form = AuthenticationForm()
		args = {'form': form}

		

		return render(request, self.template_name, args)

	def post(self, request):
		def is_leader(user):
			return user.groups.filter(name='Leader').exists()

		def is_scout(user):
			return user.groups.filter(name='Scout').exists()

		username = request.POST['username']
		password = request.POST['password']

		user = authenticate(request, username=username, password=password)
		if user is not None:
			login(request, user)
			request.session['user_username'] = username

			if is_leader(user):
				print('leader')
				redirecting_url = 'leaders:home'
				return redirect(redirecting_url)



			elif is_scout(user):
				redirecting_url = 'accounts:home'
				slug = user.userprofile.troop
				return redirect(redirecting_url, slug=slug)
			
			elif user.is_superuser:
				redirecting_url = 'admin:index'
				return redirect(redirecting_url)
			else:
				print('error')
				slug = user.userprofile.troop
				redirecting_url = 'accounts:home'
				return redirect(redirecting_url, slug=slug)

		else:
			form = AuthenticationForm()
			error = True
			args = {'form': form, 'error': error}
			return render(request, self.template_name, args)

	        
class Register(TemplateView):
	def get(request):
		form_var = RegistrationForm()
		args = {'form': form_var}
		return render(request, 'login/reg_form.html', args)
	def post(request):
		form = RegistrationForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('accounts:home', slug=user.userprofile.slug)


class Change_Password(TemplateView):
	def get(request):
		form = PasswordChangeForm(user=request.user)
		args = {'form': form}
		return render(request, 'login/change_password.html', args)		

	def post(request):
		form = PasswordChangeForm(data=request.POST, user=request.user)
		if form.is_valid():
			form.save()
			update_session_auth_hash(request, form.user)
			return redirect('accounts:view_profile', slug=user.userprofile.slug)
		else:
			return redirect("login:change_password", slug=user.userprofile.slug)

login/templates/login/login.html
{% extends "base.html" %}

{% block navbar %}
{% endblock %}
{% block body-tag %}
	<body class="text-center">{% endblock %}
{% block body %}

<div class= "container">    

  <a class="btn btn-lg btn-outline-primary" href="{% url 'home_page:home' %}" style="float: right;">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="d-block mx-auto">
          <circle cx="12" cy="12" r="10"></circle>
            <line x1="6" y1="18" x2="18" y2="6"></line>
            <line x1="6" y1="6" x2="18" y2="18"></line></svg>
        </a>
	<br>
  <br>
      <img class="mb-4" src="https://upload.wikimedia.org/wikipedia/en/thumb/8/87/World_Scout_Emblem_1955.svg/1200px-World_Scout_Emblem_1955.svg.png" alt="" width="72" height="72">
      <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
      {% if error %}
	<div class="alert alert-danger" role ="alert">
		<strong>Oh no!</strong> It seems like you may have entered your details incorrectly. Try again.
	</div>
	{% endif %}

{% if account_error %}
  <div class="alert alert-danger" role ="alert">
    <strong>Oh no!</strong> It seems we're having a problem with ylinking you up to your account. Try again and email us if the problem persists.
  </div>
  {% endif %}      
  <form method="post">
		{% csrf_token %}
		{% include 'bf_form.html' with form=form %}

     
      <input class="btn btn-lg btn-outline-primary btn-block" type="submit" value="Log In">
      <a class="btn btn-lg btn-outline-dark btn-block" href="{% url 'home_page:pricing' %}">Sign Up</a>
      <a class="btn btn-lg btn-outline-dark btn-block" href="{% url 'login:reset_password' %}">Forgot Password?</a>
      <p class="mt-5 mb-3 text-muted">©2018</p>
    </form>

  <br><br></div>
  {% endblock %}

login/templates/login/reg_form.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
	<h1>Register</h1>
	<form method='POST'>
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit">Submit</button>
	</form>
</div>
{% endblock %}

login/templates/login/reset_password.html
{% extends "base.html" %}

{% block body %}
<div class="container">
	<br>
	<h1>Password reset</h1>
	<p>
		Forgotten password? That's ok. Just enter your email address below, and we'll email instructions for setting a new one.
	</p>
	<form method="post">
		{% csrf_token %}
		{% include 'bf_form.html' with form=form %}
		<button type="submit" class="btn btn-primary">Reset password</button>
	</form>
	
</div>

</form>
{% endblock %}

login/templates/login/reset_password_complete.html
{% extends "base.html" %}

{% block body %}
<div class="container">
	<br>
	<h2>Yay! It's all done!</h2>
	<p> You can log back in <strong><a href="{% url 'login:login' %}">here.</strong></a></p>
</div>

{% endblock %}

login/templates/login/reset_password_confirm.html
{% extends "base.html" %}

{% block body %}
	{% if validlink %}
		<div class="container">
			<br>
			<h1>Enter new password</h1>
			<p>
			</p>
			<form method="post">
				{% csrf_token %}
				{% include 'bf_form.html' with form=form %}
				<button type="submit" class="btn btn-primary">Reset password</button>
			</form>
			{% else %}
    <p>
      The password reset link was invalid, possibly because it has already been used.
      Please request a new password reset.
    </p>
  {% endif %}
{% endblock %}

login/templates/login/reset_password_done.html
{% extends "base.html" %}

{% block body %}
<div class="container">
	<br>
	<h2>Sent!</h2>
	<p>
		We've emailed you instructions for reseting your password, if an account exists with the email you entered, you will receive the necessary details within it.</br>

If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder. If you're still stuck, ask a leader to try and reset your password. If all else fails feel free to send us an email <strong><a href="{% url 'home_page:contact' %}"> by going here</strong></a>. We'd be happy to help!
	</p>
</div>

{% endblock %}

login/templates/login/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}Hey there!\nYou're receiving this email because you requested a password reset for your SORB account.{% endblocktrans %}

{% trans "If this was you, please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'login:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "In case you've forgotten, your username is:" %}{{ user.get_username }}
{% trans "Thank you for using SORB" %}

{% blocktrans %}The SORB team{% endblocktrans %}
{% endautoescape %}