home/urls.py
from django.urls import include, path
from django.contrib import admin

from home.views import (
	WelcomeView, 
	PricingView, 
	Contact, 
#	SubscribeView, 
#	SuccessView,
#	index,
	ChargeView,

	)


app_name='home_page'

urlpatterns = [
	path('', WelcomeView.as_view(), name='home'),
	path('pricing/', PricingView.as_view(), name='pricing'),
#	path('pricing/payment', include('djstripe.urls', namespace="djstripe")),


#	path('pricing/checkout', CheckOutView.as_view(), name='checkout'),
	path('contact-us/', Contact.as_view(), name='contact'),
#	path('thank_you/', SuccessView.as_view(), name='thank_you'),
#	path('subscribe/', SubscribeView.as_view(), name='subscribe'),

	path('pricing/paid/', ChargeView.as_view(), name='paid'),
]

leaders/urls.py
from django.urls import path
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns



from leaders.badge_requests import (
	SpecificBadgeRequestView_1,

	)
from leaders.views import (

	HomeView, 
	RequestBadgeQuantityView,
	SubmitedView,
	ScoutView,

	Badge_Report,
	Report_Quantity,
	TestView,
	ContactView,


)
from leaders import views



app_name="leaders"

urlpatterns = [
	path('', HomeView.as_view()
		, name='home'),

	path('badge_request_quantity', RequestBadgeQuantityView.as_view(), name="badge_request_quantity"),
	path('badge_request_quantity/<int:quantity>', SpecificBadgeRequestView_1.as_view(), name="specific_badge_request"),

	path('badge_request_quantity/success', SubmitedView.as_view(), name="redirect"),

	path('test', TestView.as_view(), name="test"),
	path('badge_report_<int:month>', Badge_Report.as_view(), name="badge_report"),
	path('badge_report_quantity', Report_Quantity.as_view(), name="Report_Quantity"),

		path('contact', ContactView.as_view(), name="contact"),

] + staticfiles_urlpatterns()

scouts/urls.py
from django.urls import include, path
from django.contrib import admin
from scouts.views import Login_Error_redirect
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.conf import settings
from django.conf.urls.static import static

main_urls = [
path('account/', include('accounts.urls', namespace='accounts'))
    
]


urlpatterns = [
#    path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('leaders/scout_info/', admin.site.urls),
    path('leaders/', include('leaders.urls', namespace='leaders')),

    path('account/', Login_Error_redirect.as_view(), name="accounts_redirect"),
    path('', include('home.urls', namespace='home_page')),
    path('login/',  include('login.urls', namespace='login')),
    path('record_book/', include('record_book.urls', namespace='record_book')),
    path('<slug:slug>/', include(main_urls))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

leaders/forms.py
from django import forms
from leaders.models import ScoutData, ScoutDataManager
from django.contrib.auth.models import User
from accounts.models import UserProfileManager, UserProfile

	#user1 = User.objects.get(username ='user1')

	#scout_username_list=[
	#	(None, 'Choose a scout'),
	#	(scout_user, 'user1'),
	#	(i, 'no progress'),
	#	]


# Create your models here.
class EmailForm(forms.Form):


#	email = forms.EmailField(required=True,
#		label='Email:',
#		error_messages={'required': 'It helps to have your email'},		
#)

	GroupChoices = (
		('Scouts', 'Scouts',),
		('Leader', 'Leaders',),
		('All', 'All',)
		)
	group = forms.ChoiceField(
		required=True,
		widget=forms.RadioSelect(attrs={'id':'group_radio'}),
		choices=GroupChoices,
		)

	subject = forms.CharField(required=True, 
		label='Subject:',
		error_messages={'required': 'Please select subject'},
		)

	message = forms.CharField(required=True, 
		label='Message:', 
		widget=forms.Textarea,
		max_length='500',
		min_length='10',
		error_messages={'required': "What do you wanna say?"},		

		)
class BadgeForm(forms.ModelForm):

#	def get_user(self, user):
#		self.user = user
#	def set_user(self, user):
#		global scout_username_list
#		query = User.objects.all()
#		troop = user.userprofile.troop
#		userprofile = UserProfile.objects.all()
#		selected_scouts = userprofile.filter(troop=troop)
#		for scout in selected_scouts:
#			username = str(scout.scout_username)

#			scout_username_list.append((username, username))


	
		
#		query = User.objects.filter(scout_username__username__in=display_list)

#	scout_username = forms.ChoiceField(choices=scout_username_list)

	class Meta:
		model = ScoutData
		fields = ('scout_username', 'Pioneer_Badge', 'Explorer_Badge', 'Adventurer_Badge', 'Proficiency_Badge', 'Other_Badge') 
		#comma is necessary because of tuple unpacking x,y = (1,2) - leaves it as a tuple

	#filters the accessible scouts
	def __init__(self, user=None, *args, **kwargs):
#		self.user = kwargs.pop("user")
		self.user = user

		super(BadgeForm, self).__init__(*args, **kwargs)
#		self.fields['scout_username'].queryset = UserProfile.objects.filter(troop='BC')
		self.fields['scout_username'].queryset = User.objects.filter(userprofile__troop=user.userprofile.troop, userprofile__role='Scout')


#	def clean(self):
#		cleaned_data = super().clean()
#		Pioneer_Badge = cleaned_data.get('Pioneer_Badge')
#		Explorer_Badge = cleaned_data.get('Explorer_Badge')
#		Adventurer_Badge = cleaned_data.get('Adventurer_Badge')
#
#		if '' in Pioneer_Badge and '' in Explorer_Badge and '' in Adventurer_Badge:
#			msg = "Please select at least 1 badge"
#			self.add_error('Pioneer_Badge', msg)
#			self.add_error('Explorer_Badge', msg)
#			self.add_error('Adventurer_Badge', msg)
'''
	user1 = User.objects.get(username ='user1')

	st_username_list=[
		(None, 'Choose a user'),
		(user1, 'user1'),
		(i, 'no progress'),
		]

	class BadgeForm(forms.ModelForm):
		def set_user(self, user):
			global st_username_list
			troop = user.userprofile.troop
			userprofile = UserProfile.objects.all()
			selected_st = userprofile.filter(troop=troop)
			for st in selected_st:
				username = str(st.st_username)
				st_username_list.append((username, username))
		st_username = forms.ChoiceField(choices=st_username_list)
		class Meta:
			model = stData
			fields = ('st_username', 'Pioneer_Badge', 'Explorer_Badge', 'Adventurer_Badge', 'Proficiency_Badge', 'Other_Badge') 
			#comma is necessary because of tuple unpacking x,y = (1,2) - leaves it as a tuple

	'''	

home/views.py
from django.views.generic import TemplateView, FormView
from django.shortcuts import render, redirect, get_object_or_404

from django.utils.decorators import method_decorator
from django.contrib.admin.views.decorators import staff_member_required

from home.form import StripeForm, BTroopSignup, PTroopSignup, PricingFormA, PricingFormB
from django.conf import settings
from django.contrib.auth.models import User

from home.models import ContactForm, Payments
from accounts.models import UserProfile, GroupRecord
from django.core.mail import EmailMessage, send_mail
from django.template.loader import get_template
from scouts import settings
import stripe, bs4, time
'''
stripe_keys = {
	'secret_key': settings.STRIPE_TEST_SECRET_KEY,
	'publishable_key': settings.STRIPE_TEST_PUBLIC_KEY
}
stripe.api_key = stripe_keys['secret_key']
'''

def blank_field(packaged_errors):
	blank = False
	blank_arr = {}
	passed_list = []
	for i in range(0, len(packaged_errors)):
		for mini_i in range(0, len(packaged_errors[i][1])):
			if 'field blank' in packaged_errors[i][1][mini_i]:
				blank_arr[i] = True

	for el in range(0, len(blank_arr)):
		#if el == 0 because the first field was not blank
		#So check if field was blank by checking if el is in blank array

		if el in blank_arr:
			passed_list.append(blank_arr[el])
	print (passed_list)
	if len(passed_list) >= 3:
		blank = True
	return blank


def error_packaging(error):
	empty_l = []
	l_error = list(error)
	for i in range(0, len(list(error))):
		if 'Troop_id' in l_error[i]:
			key = 'Troop Name'
		elif 'Troop_abr' in l_error[i]:
			key = 'Troop Abbreviation'
		elif 'Troop_fd_date' in l_error[i]:
			key = 'Foundation Date'
		empty_l.append(list((key, error[l_error[i]])))
	return empty_l

class WelcomeView(TemplateView):
	template_name = 'home/home_page.html'

	def get(self, request):

		#refreshing teh databases
		#the grouprecord one first
		
		'''
		unecessary
		_new_group, ng_created = GroupRecord.objects.get_or_create(group='Admin3', 
									abbreviation='N/A3', subscription='Premium')
								if ng_created:
									_new_group.save()
								temp_user, user_created = User.objects.get_or_create(username='temp_user5', password='temp2018', is_staff=True)
								if user_created:
									temp_user.save()
								#up refers to userprofile
								temp_user.userprofile.scout_username = temp_user
								temp_user.userprofile.role= 'Leader'
								temp_user.userprofile.troop = _new_group.group
								temp_user.userprofile.save()
								temp_user.delete()
								_new_group.delete()'''
		#to do
		#check if troop name is already in database, if so, retrieve its master login
		#else
		#Create a Master Login
		#Add Troop Name as a new troop within the database

		amount = request.session.get('amount', '0')
		signup = request.session.get('signup', False)
		email = request.session.get('contact_email', 'an incorrect email address')

		#clearing of session variables
		request.session['amount'] = 0
		request.session['email'] = ''
		request.session['signup'] = False
		args = {
		'key': settings.STRIPE_TEST_PUBLIC_KEY,
		'signup': signup,
		'amount': amount,
		'email': email
		}
		return render(request, self.template_name, args)

class OldPricingView(TemplateView):
	template_name = 'home/pricing.html'

	def get(self, request):
		stripe.api_key = settings.STRIPE_TEST_SECRET_KEY
		args = {'key': settings.STRIPE_TEST_PUBLIC_KEY,
			'form_b': BTroopSignup(), 'form_p': PTroopSignup()
		}
		return render(request, self.template_name, args)

	def post(self, request):
		form_pass_valid = False

		print ("POSTED")
		stripe.api_key = settings.STRIPE_TEST_SECRET_KEY

#		print (request.form['text'])
		form_info_b = BTroopSignup(request.POST)
		form_info_p = PTroopSignup(request.POST)

		if form_info_b.is_valid():
			form_pass_valid = True
			request.session['Troop_id'] = form_info_b.cleaned_data['BasicTroop_id']
			request.session['Troop_abr'] = form_info_b.cleaned_data['BasicTroop_abr']
			request.session['Troop_fd_date'] = form_info_b.cleaned_data['BasicTroop_fd_date']

			amount = 1200

		elif form_info_p.is_valid():
			form_pass_valid = True

			request.session['Troop_id'] = form_info_p.cleaned_data['PremTroop_id']
			request.session['Troop_abr'] = form_info_p.cleaned_data['PremTroop_abr']
			request.session['Troop_fd_date'] = form_info_p.cleaned_data['PremTroop_fd_date']

			amount = 1600
			
		if form_pass_valid:
			contact_email = request.POST['stripeEmail']

			customer = stripe.Customer.create(
				email=contact_email,
				source=request.POST['stripeToken'],
				api_key = settings.STRIPE_TEST_SECRET_KEY
				)
			charge = stripe.Charge.create(
				customer = customer.id,
				amount=amount,
				currency='aud',
				description='Flask Charge'
				)
			
			r_amount = float((str(amount))[:-2] + "." + (str(amount)[-2:]))

			request.session['amount'] = r_amount 
			request.session['contact_email'] = contact_email	
			return redirect ('home_page:paid')
		else:
			#html list of errors

			#form b errors
			errors_p = form_info_p.errors
			error_list_p = error_packaging(errors_p)
			print ('form P Errors: \n' + str(error_list_p))

			#creates a dictionary where the key is a new key with a human readble name

			#form b errors
			errors_b = form_info_b.errors
			error_list_b = error_packaging(errors_b)
			print ('form B Errors: \n' + str(error_list_b))

			args = {'key': settings.STRIPE_TEST_PUBLIC_KEY,
			'form_p': BTroopSignup(), 
			'form_b': PTroopSignup(), 
			'error': True,
			'error_b': error_list_b, 'error_p': error_list_p,
			}
			return render(request, self.template_name, args)

'''
class CheckOutView(TemplateView):
	stripe.api_key = settings.STRIPE_TEST_SECRET_KEY
	new_payment = Payments(
			plan = "Stadard")

	def get(self, request):
		payment.save()
		return redirect('home_page:home')

	def post(self, request):
		token = request.POST.get("stripeToken")
		try:
			charge  = stripe.Charge.create(
				amount = 1600,
				currency = "aud",
				source = token,
				description = "standard plan"
			)

		new_payment.charge_id = charge.id

		except stripe.error.CardError as ce:
			return False, ce
		
'''
class Contact(TemplateView):
	template_name = 'home/contactUs.html'

	def get(self, request):
		form = ContactForm()
		args = {'form': form}
		return render(request, self.template_name, args)

	def post(self, request):
		form = ContactForm()		
		args = {'form': form}
		
		form_info = ContactForm(request.POST)
		if form_info.is_valid():
			first_name = request.POST.get('first_name', '')
			last_name = request.POST.get('last_name', '')
			email_address = request.POST.get('email', '')
			subject = request.POST.get('subject', '')
			message = request.POST.get('message', '')

			# email the profile with contact info
			
#			template = get_template('contact_template.txt')
#			context = {
#			'first_name': first_name,
#			'last_name': last_name,
#			'email': email,
#			'subject': subject,
#			'message': message,
#			}
#			content = template.render(context)
#			email = EmailMessage(
#				"New contact form submission",
#				content,
#				subject +'',
#				['youremail@gmail.com'],
#				headers = {'Reply-To': email }
#			)
#			email.send()
			email = EmailMessage (
				subject = subject,
				body=('You have a query:\n{}\nFrom\n{} {}'.format(message, first_name, last_name)),
				from_email='email.service@sorb.com.au',
				reply_to=[email_address],
				to=['felix.p.hall@gmail.com',],
				headers={'Content-Type': 'text/plain'})
			email.send()

			args.update({'success':True})
		return render(request, self.template_name, args)
			

class PricingView(TemplateView):
	template_name = 'home/pricing2.html'
	
	def get(self, request):
		stripe.api_key = settings.STRIPE_TEST_SECRET_KEY

		args = {
			'key': settings.STRIPE_TEST_PUBLIC_KEY,
			'formA': PricingFormA(), #Premium
			'formB': PricingFormB() #Basic
		}
		return render(request, self.template_name, args)
	def post(self, request):
		valid_form = False
		form_used = None
		stripe.api_key = settings.STRIPE_TEST_SECRET_KEY

#		print (request.form['text'])
		form_info_a = PricingFormA(request.POST)
		form_info_b = PricingFormB(request.POST)

		if form_info_b.is_valid():
			p_name = 'Basic'

			form_used = 'B'
			valid_form = True
			amount = 0000
			plan = stripe.Plan.retrieve("plan_DLIn5NDMMMdMHj")

			request.session['Troop_id'] = form_info_b.cleaned_data['Test_BTroop_id']
			request.session['Troop_abr'] = form_info_b.cleaned_data['Test_BTroop_abr']
			request.session['Troop_fd_date'] = form_info_b.cleaned_data['Test_BTroop_fd_date']
			contact_email = form_info_b.cleaned_data['Test_BTroop_email']

			print('Form B:')
			print (request.session.get('Troop_id', 'Nothing sorry'))

		elif form_info_a.is_valid():
			form_used = 'A'
			print ('form A')

			amount = 1600
			plan = stripe.Plan.retrieve("plan_DLIkKZNvTGqfCg")
			p_name = 'Premium'
			valid_form = True

			request.session['Troop_id'] = form_info_a.cleaned_data['Test_ATroop_id']
			request.session['Troop_abr'] = form_info_a.cleaned_data['Test_ATroop_abr']
			request.session['Troop_fd_date'] = form_info_a.cleaned_data['Test_ATroop_fd_date']
			print('Form A:')
			print (request.session.get('Troop_id', 'Nothing sorry'))			

#			to fix up later
			timestamp = (int(time.time()) + 120) 

			contact_email = request.POST['stripeEmail']

			customer = stripe.Customer.create(
				email=contact_email,
				source=request.POST['stripeToken'],
				api_key = settings.STRIPE_TEST_SECRET_KEY
				)
#			charge = stripe.Charge.create(
#				customer = customer.id,
#				amount=amount,
#				currency='aud',
#				)

			
			subscription = stripe.Subscription.create(
				customer=customer.id,
				items=[
					{
				    "plan": plan,
				    },
				  ],
				trial_period_days = 30,

				)
		if valid_form:

			r_amount = float((str(amount))[:-2] + "." + (str(amount)[-2:]))
			new_leader = None
			request.session['amount'] = r_amount 
			request.session['contact_email'] = contact_email
			request.session['signup'] = True	

scouts/views.py
from django.contrib.auth.models import User
from django.views.generic import TemplateView


from django.urls import reverse

class Login_Error_redirect(TemplateView):
	def get(self, request):
		return redirect('login:login')

leaders/templates/leaders/badge_request_quantity.html
{% extends 'admin/base_site.html' %}

{% block content %}
<style type="text/css">
a:link, a:visited {
  color: white;
  text-decoration: none;
  }
</style>
<div class="container">
	<h2>Tell us, how many new badges have been finished?</h2><br>

	<div class="btn-toolbar" role="toolbar" aria-label="1-4 scouts" >
		
	  <div class="btn-group mr-2" role="group" aria-label="First group">
	    <a class="btn btn-info" id="buttons"  href="{% url 'leaders:specific_badge_request' quantity=1  %}">1</a>
	    <a class="btn btn-info" id="buttons" href="{% url 'leaders:specific_badge_request' quantity=2  %}">2</a>
	    <a class="btn btn-info" id="buttons" href="{% url 'leaders:specific_badge_request' quantity=3  %}">3</a>
	    <a class="btn btn-info" id="buttons" href="{% url 'leaders:specific_badge_request' quantity=4  %}">4</a>
		</div>
	{% if PremiumAccess %}

		<div class="btn-group mr-2" role="group" aria-label="Second group">
	    <a class="btn btn-info" id="buttons" href="{% url 'leaders:specific_badge_request' quantity=5  %}">5</a>
	    <a class="btn btn-info" id="buttons" href="{% url 'leaders:specific_badge_request' quantity=6  %}">6</a>
	    <a class="btn btn-info" id="buttons" href="{% url 'leaders:specific_badge_request' quantity=7  %}">7</a>
	    <a class="btn btn-info" id="buttons" href="{% url 'leaders:specific_badge_request' quantity=8  %}">8</a>
		</div>

	    <div class="btn-group" role="group" aria-label="Third group">
	    <a class="btn btn-info" id="buttons" href="{% url 'leaders:specific_badge_request' quantity=9  %}">9</a>
	    <a class="btn btn-info" id="buttons" href="{% url 'leaders:specific_badge_request' quantity=10  %}">10</a>
	    <a class="btn btn-info" id="buttons" href="{% url 'leaders:specific_badge_request' quantity=11  %}">11</a>
	    <a class="btn btn-info" id="buttons" href="{% url 'leaders:specific_badge_request' quantity=12  %}">12</a>
	  </div>	
{% endif %}

</div>
<br>
<br><br>

{% endblock %}

leaders/templates/leaders/badge_request_specifics.html
{% extends 'admin/base_site.html' %}

{% block content %}
<style type="text/css">
a:link, a:visited {
  color: white;
  text-decoration: none;
  }
</style>
	<br><h2>Thank you! Here's the form you need:</h2><br>
	
	<form method="post">
		{% csrf_token %}
		{{ formset.management_form }}
		<div class ="row">
		{% for form in formset %}
		<div class="col"> 
		{{ form.as_p }}
		<br>
		</div>
		{% endfor %}
	</div>
		<button type="submit" name="submit" class="btn btn-info">Submit</button>
	</form> 

{% if error %}
	<div class="alert alert-danger" role="alert">
  <strong>Oh no!</strong> It looks like you forgot to select a badge. Clicking submit will submit the filled in fields, but do nothing to the ones you forgot.<a href="{% url 'leaders:badge_request_quantity'%}" class="alert-link">You could add the ones you forgot by clicking here.</a>
</div>
{% endif %}

{% if safe %}
<div class="alert alert-info" role="alert">
  <strong>Almost Done!</strong> Your data has been passed through the validations. Just click submit again, and it's all done!
</div>
{% endif %}

</div>
<br>
<br><br>

{% endblock %}

leaders/templates/leaders/contact.html
{% extends 'admin/base_site.html' %}

{% block pagestyling %}
<style type="text/css">
	#group_radio{
    display: grid;
    align-content: inline;
    vertical-align: top;
    grid-template-rows: 25%;
    grid-template-columns: 1fr 1fr 1fr;
}
</style>
{% endblock %}

{% block content_title %}
<div class ="container">
{% endblock %}

{% block content %}
{% if success %}
<div class="alert alert-success" role="alert">
  <strong>Success!</strong> Do you want to head back to the<a href="{% url 'leaders:home' %}" class="alert-link"> Home Page.</a>
</div>
{% endif %}
<div class="container">
<h2>Contact your troop:</h2>
<div class ="form-group">
<form role="form" method="post">
    {% csrf_token %}
        {% include 'bf_form.html' with form=form %}
 <button type="submit" class="btn btn-primary">Send now!</button></form></div>
    </br>
</div>
<br>
<br><br>


<script type="text/javascript">
$(function(){
	$('#group_radio').removeClass("form-control").addClass("container");
	$('#group_radio').contents().replaceWith(function(){
		return $("<div />", {html: $(this).html()});
	});
	$('#group_radio div:empty').remove();
	$('#group_radio div').css({'justify-self': 'center'});
	//replaceWith(function(){
	});

</script>
{% endblock %}

leaders/templates/leaders/form_redirect.html
{% extends 'admin/base_site.html' %}

{% block content %}
<style type="text/css">
a:link, a:visited {
  color: white;
  text-decoration: none;
  }
</style>
<br>
<h3>Would you like to go back to the home page or tick off another badge?</h3>
	

<a href="{% url 'leaders:badge_request_quantity'  %}" class="btn btn-success btn-lg btn-block"  role="button" aria-pressed="true"><strong>More badgework</strong></a>
<a href="{% url 'leaders:home' %}" class="btn btn-success btn-lg btn-block"  role="button" aria-pressed="true" ><strong>Home page</strong></a>

</div>
<br>
<br><br>

{% endblock %}

leaders/templates/leaders/home.html
{% extends 'admin/base_site.html' %}

{% block pagestyling %}

{% endblock %}

{% block content_title %}
<div class ="container">
<h1>Welcome!</h1></div>
{% endblock %}

{% block content %}
<style type="text/css">
a:link, a:visited {
  color: white;
  text-decoration: none;
  }
</style>
<div class="container">

	<h2>What do you feel like doing today?</h2>
<!-- changer couleur -->
	<div>
	<a href="{% url 'leaders:badge_request_quantity'  %}" class="btn btn-info btn-lg btn-block"  role="button" id="buttons" aria-pressed="true"><strong>Badgwork</strong></a>
	<a href="{% url 'admin:index'  %}" class="btn btn-info btn-lg btn-block"  role="button" id="buttons" aria-pressed="true"><strong>Scout progress/Accounts</strong></a>
	{% if PremiumAccess %}
	<a href="{% url 'leaders:Report_Quantity'  %}" class="btn btn-info btn-lg btn-block"  role="button" id="buttons" aria-pressed="true"><strong>Badge report</strong></a>
	<a href="{% url 'leaders:contact'  %}" class="btn btn-info btn-lg btn-block"  role="button" id="buttons" aria-pressed="true"><strong>Contacting troop</strong></a>
</div>
	{% endif %}

</div>
<br>
<br><br>

{% endblock %}

leaders/templates/leaders/report_quantity.html
{% extends 'admin/base_site.html' %}

{% block pagestyling %}

	{% endblock %}
{% block content %}
<style type="text/css">
a:link, a:visited {
  color: white;
  text-decoration: none;
  }
</style>
<div class="container">
	<h2>In terms of months, what time frame do you whish to be included within the report?</h2><br>

	<div class="btn-toolbar" role="toolbar" aria-label="1-3 months" id="buttons">
		
	  <div class="btn-group mr-2" role="group" aria-label="First group">
	    <a class="btn btn-info" href="{% url 'leaders:badge_report' month=1  %}">1</a>
	    <a class="btn btn-info"href="{% url 'leaders:badge_report' month=2  %}">2</a>
	    <a class="btn btn-info"href="{% url 'leaders:badge_report' month=3  %}">3</a>

		</div>

		<div class="btn-group mr-2" role="group" aria-label="Second group">
	    <a class="btn btn-info"href="{% url 'leaders:badge_report' month=4  %}">4</a>
	    <a class="btn btn-info"href="{% url 'leaders:badge_report' month=5  %}">5</a>
	    <a class="btn btn-info"href="{% url 'leaders:badge_report' month=6  %}">6</a>
	</div>
</div>
<br>
<br><br>

{% endblock %}

leaders/templates/leaders/scout_view.html
{% extends 'base.html' %}

{% block extrastyle %}
<!-- Bootstrap stuff -->
		<link rel="stylesheet" 
		href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" 
		integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" 
		crossorigin="anonymous">
		<!-- Responsive meta tag -->
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		{% block pagestyling %}{% endblock %}

{% endblock %}

{% block body %}
<div class="container">
	<h2>View and edit the scout progress by induvidual scouts</h2>

</div>
{% endblock %}

leaders/templates/leaders/test.html
{% extends 'admin/base_site.html' %}

{% block pagestyling %}

{% endblock %}

{% block content_title %}
<div class ="container">
<h1>Welcome!</h1></div>
{% endblock %}

{% block content %}

<div class="container">

	<h2>Results from query:</h2>
	{{ data }}

</div>
<br>
<br><br>

{% endblock %}