accounts/urls.py
from django.urls import path, re_path
from . import views

from accounts.badge_views import Pioneer, Explorer, Adventurer



app_name="accounts"

urlpatterns = [
	path('', views.home, name="home"), 
	#account authenticating
 	path('logout/', views.logout_view, {'template_name': 'accounts/logout.html'}, name='logout'),
	#profile details
	path('profile/', views.view_profile, name='view_profile'),
	path('profile/edit/', views.edit_profile, name="edit_profile"),
	#password details
	path('profile/password/', views.change_password, 
		name="change_password"),

	#badges
	path('pioneer-progress/', Pioneer.as_view(), name='pioneer_progress'),
	path('explorer-progress/', Explorer.as_view(), name='explorer_progress'),
	path('adventurer-progress/', Adventurer.as_view(), name='adventurer_progress'),

	] 

home/urls.py
from django.urls import include, path
from django.contrib import admin

from home.views import (
	WelcomeView, 
	PricingView, 
	Contact, 
#	SubscribeView, 
#	SuccessView,
#	index,
	ChargeView,

	)


app_name='home_page'

urlpatterns = [
	path('', WelcomeView.as_view(), name='home'),
	path('pricing/', PricingView.as_view(), name='pricing'),
#	path('pricing/payment', include('djstripe.urls', namespace="djstripe")),


#	path('pricing/checkout', CheckOutView.as_view(), name='checkout'),
	path('contact-us/', Contact.as_view(), name='contact'),
#	path('thank_you/', SuccessView.as_view(), name='thank_you'),
#	path('subscribe/', SubscribeView.as_view(), name='subscribe'),

	path('pricing/paid/', ChargeView.as_view(), name='paid'),
]

login/urls.py
from django.urls import path, re_path, reverse_lazy
from login import views
from login.views import Login, Register

from django.contrib.auth.views import (
	LoginView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, 
	PasswordResetCompleteView
	)
from django.shortcuts import redirect


app_name="login"

urlpatterns = [
	path('', Login.as_view(), name='login'),
	#setting up accounts, to look over later
	path('register', Register.as_view(), name='register'),
	path('reset-password/', PasswordResetView.as_view(
		template_name= 'login/reset_password.html', 
		success_url= 'done/', 
		email_template_name= 'login/reset_password_email.html',
		), name='reset_password'),

	path('reset-password/done/', PasswordResetDoneView.as_view( 
		template_name= 'login/reset_password_done.html'), name='password_reset_done'),
	
	re_path(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', 
		PasswordResetConfirmView.as_view(
			template_name= 'login/reset_password_confirm.html', 
			success_url= reverse_lazy('login:password_reset_complete')),
			
		name='password_reset_confirm'),

	path('reset-password/complete/', PasswordResetCompleteView.as_view( 
		template_name= 'login/reset_password_complete.html'),
	 name="password_reset_complete"),

	] 

scouts/urls.py
from django.urls import include, path
from django.contrib import admin
from scouts.views import Login_Error_redirect
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.conf import settings
from django.conf.urls.static import static

main_urls = [
path('account/', include('accounts.urls', namespace='accounts'))
    
]


urlpatterns = [
#    path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('leaders/scout_info/', admin.site.urls),
    path('leaders/', include('leaders.urls', namespace='leaders')),

    path('account/', Login_Error_redirect.as_view(), name="accounts_redirect"),
    path('', include('home.urls', namespace='home_page')),
    path('login/',  include('login.urls', namespace='login')),
    path('record_book/', include('record_book.urls', namespace='record_book')),
    path('<slug:slug>/', include(main_urls))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from crequest.middleware import CrequestMiddleware
from slugger import AutoSlugField

from django.template.defaultfilters import slugify
from django.contrib.auth.models import User, Group
from django.db.models.signals import post_save
from datetime import date
import inspect, os
from django.dispatch import receiver


#from login.groups import Groups as gp

# Create your models here.

'''
created with the purpose of retrieving the GroupRecord data so that the model will update. Did not work
class GroupDataRetriever():
	def __init__(self):
		list_format_group = [(None, 'Click here to select the group')]
		self.list_format_group = list_format_group
		
		tuple_format_group = tuple(self.list_format_group)
		
		Group_Choice = tuple_format_group
		self.Group_Choice = Group_Choice 

	def refreshed(self):
		self.slug = slugify(self.troop_details)


	def retrieve(self):
		print ('updated')
		print (self.Group_Choice)
		return self.Group_Choice fix '''


def list_maker(abbr, name):
	list_group = (str(abbr), str(name))
	return list_group

class GroupRecord(models.Model):
	plan_choice = (
		('Basic', 'Basic'),
		('Premium', 'Premium')
		)
	group = models.CharField(max_length=100, default='None')
	abbreviation = models.CharField(max_length=80)
	subscription = models.CharField(choices=plan_choice, max_length=8, default='Basic', blank=False)



	def __str__(self):
		return '%s'% (self.group)


def Scout_Groups():
		
		scout_group_list = (
		(None, 'Click here to select the group'),
		('BC', 'Brisbane Central Scout'),
		('Admin', 'N/A'),

		)
		return scout_group_list

'''
class UserProfileAdminManager(models.AdminManager):
	def get_query_set(self, request):
		return super(UserProfileAdminManager, self).get_query_set().filter(troop=request.user.userprofile.troop)
'''
class UserProfile(models.Model):

	def __init__(self, *args, **kwargs):
		super(UserProfile, self).__init__(*args, **kwargs)

		#print ('REFRESHED')
		
		
	#data = GroupDataRetriever()
	role_choice = (
		('Leader', 'Leader'),
		('Scout', 'Scout')
		)
	list_format_group = [(None, 'Click here to select the group')]

	#list_format_group = []
	'''
	Making a list of selection for users to select their troop from
	data_set = GroupRecord.objects.all()
				#print (data_set)
				for i in data_set:
					group_name = i.group
					group_abbr = i.abbreviation
					list_format_group.append(list_maker(group_abbr, group_name)) fix'''
	'''tuple_format_group = tuple(list_format_group)
				
				Group_Choice = tuple_format_group'''
		


	print ('called userprofile')
	troop_details = models.ForeignKey(GroupRecord, on_delete=models.CASCADE, unique=False, null=True)
	#troop_details = models.SlugField(max_length=27, choices=Group_Choice, default='None', blank=False)
	troop = models.SlugField(max_length=75, unique=False, null=True)
	role = models.CharField(choices = role_choice, max_length=7, default='Scout', blank=False)
	date_of_birth = models.DateField(default=date.today, null=True)
	secondary_email = models.EmailField(blank=True, unique=True, null=True, max_length=250)
	scout_username = models.OneToOneField(User, on_delete=models.CASCADE, unique=True) 


	def __str__(self):
		return '%s'% (self.scout_username)

		
	def save(self, *args, **kwargs):
		#slugifying the troop
		self.troop = slugify(self.troop_details)
		

		Leader_group = Group.objects.get(name="Leader")
		Scout_group = Group.objects.get(name="Scouts")

		Premium_group = Group.objects.get(name="Premium")
		Basic_group = Group.objects.get(name="Basic")
		CurrentTroopData = GroupRecord.objects.filter(group=self.troop_details)

		user = self.scout_username
		user.groups.clear()
		if self.role == 'Leader':
			Leader_group.user_set.add(user)
		elif self.role == 'Scout':
			Scout_group.user_set.add(user)
		else:
			pass
		if (CurrentTroopData.filter(subscription="Premium").exists()):
			Premium_group.user_set.add(user)
		elif (CurrentTroopData.filter(subscription="Basic").exists()):
			Basic_group.user_set.add(user)
		else:
			pass 
		super(UserProfile, self).save(*args, **kwargs)

def create_user_profile(sender, instance, created, **kwargs): 
	if created:
		print ('instance is: {}'.format(instance))

		for entry in reversed(inspect.stack()):
			#print (entry[0].f_locals['request'].user)
			try:
				current_request = CrequestMiddleware.get_request()
				#user = None
				user = current_request.user
				#user = entry[0].f_locals['request'].user
			except:
				user = None
			break
		print ('user: {}'.format(user))
		if user:
			try:
				#print ('yay')
				UserProfile.objects.create(scout_username=instance, 
					troop=user.userprofile.troop, troop_details=user.userprofile.troop_details)
			except (AttributeError):

				UserProfile.objects.create(scout_username=instance) 
				#do not create now
				#then create in views
				pass
			
		else:
			UserProfile.objects.create(scout_username=instance)
	instance.userprofile.save()


post_save.connect(create_user_profile, sender=User)

class UserProfileManager(models.Manager):
	def get_queryset(self, request):
		query =	UserProfile.objects.filter(troop=request.user.userprofile.troop)
		if request.user.is_superuser:
			query = UserProfile.objects.all()
		return query

class UserManager(models.Manager):
	def get_queryset(self, request):
		query =	User.objects.filter(userprofile__troop=request.user.userprofile.troop)
		if request.user.is_superuser:
			query = User.objects.all()
		return query

'''
class ScoutUser(AbstractUser):
	list_format_group = [(None, 'Click here to select the group')]
	data_set = GroupRecord.objects.all()
	for i in data_set:
		group_name = i.group
		group_abbr = i.abbreviation
		list_format_group.append(list_maker(group_abbr, group_name))
	tuple_format_group = tuple(list_format_group)
	scout_username = models.OneToOneField(User, on_delete=models.CASCADE, unique=True)
	Group_Choice = tuple_format_group
	role_choice = (
		('Leader', 'Leader'),
		('Scout', 'Scout')
		)
#	troop = models.ForeignKey(GroupRecord, on_delete=models.CASCADE, null=True)
	troop = models.SlugField(max_length=27, choices=Group_Choice, default='None', blank=False)
	role = models.CharField(choices = role_choice, max_length=7, default='Leader', blank=False)
	date_of_birth = models.DateField(default=date.today, null=True)
'''

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class RegistrationForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = (
			'username', 
			'first_name',
			'last_name',
			'email',
			'password1',
			'password2'
			)

	def save(self, commit=True):
		user = super(RegistrationForm, self).save(commit=False)
		user.first_name = self.cleaned_data['first_name']
		user.last_name = self.cleaned_data['last_name']
		user.email = self.cleaned_data['email']

		if commit:
			user.save()

		return user

class EditProfileForm(UserChangeForm):

	def __init__(self, *args, **kwargs):
		super(EditProfileForm, self).__init__(*args, **kwargs)
		self.fields['first_name'].required = True
		self.fields['last_name'].required = True
		self.fields['email'].required = True

	class Meta:
		model = User
		fields = (
			'first_name',
			'last_name',
			'email',
			'password'
			)

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from accounts.forms import EditProfileForm

from accounts.badge_views import Percentager, DataListRequest

from django.urls import reverse

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from accounts.models import UserProfile, UserProfileManager


def logout_view(request, **kwargs):
	return redirect('home_page:home')

# Create your views here

#home view
def home(request, **kwargs):
#	user_var = request.user
#	queryset = UserProfile.objects.filter(scout_username=user_var)
#	slug_name = get_object_or_404(queryset, slug=slug)
#	print (slug_name)
	slug = request.user.userprofile.troop
	pioneer_empty = False
	explorer_empty = False
	adventurer_empty = False

	#displays the percentage progress in each section
	pioneer_progress = Percentager.Pioneer(request)
	explorer_progress = Percentager.Explorer(request)
	adventurer_progress = Percentager.Adventurer(request)

	#get the badges for each section
	pioneer_badges = DataListRequest.Pioneer(request)
	explorer_badges = DataListRequest.Explorer(request)
	adventurer_badges = DataListRequest.Adventurer(request)

	#if it was actually empty
	if len(pioneer_badges) == 0:
		pioneer_empty = True
	elif len(explorer_badges) == 0:
		explorer_empty = True
	elif (adventurer_badges) == 0:
		adventurer_empty = True

	
	args = {'slug_arg': slug, 'user': request.user, 
	'pioneer_progress': pioneer_progress, 
	'explorer_progress':explorer_progress, 
	'adventurer_progress':adventurer_progress,
	'pioneer_badges': pioneer_badges,
	'explorer_badges': explorer_badges,
	'adventurer_badges':adventurer_badges,
	'pioneer_empty': pioneer_empty,
	'explorer_empty': explorer_empty,
	'adventurer_empty': adventurer_empty,
	}
	return render(request, 'accounts/home.html', args)




def view_profile(request, **kwargs):
	# a page so the scouts can see their profile
	slug = request.user.userprofile.troop
	Editform = EditProfileForm()
	Passform = PasswordChangeForm(user=request.user)

	args = {'user': request.user, 'slug_arg': slug,
	'Passform': Passform, 'Editform': Editform, 'error': False, 'success': False}

	if request.method == 'POST':
		Passform = PasswordChangeForm(data=request.POST, user=request.user)
		Eform = EditProfileForm(request.POST, instance=request.user)

		if Passform.is_valid():
			Passform.save()
			update_session_auth_hash(request, Passform.user)
			args['success'] = True
			

		elif Editform.is_valid():
			Editform.save()
			args['success'] = True
		elif not(Editform.is_valid) and not(Passform.is_valid):
			args['error'] = True


	return render(request, 'accounts/profile.html', args)

def edit_profile(request, **kwargs):
	#A page where they can edit some of their details, 
	# To-Do: refine it so only certain details are editable
	slug = request.user.userprofile.troop
	if request.method == 'POST':
		Eform = EditProfileForm(request.POST, instance=request.user)

		if Editform.is_valid():
			Editform.save()
			return redirect('accounts:view_profile', slug=slug)
	else:
		Editform = EditProfileForm()
		args = {'Editform': Editform}
	return render(request, 'accounts/edit_profile.html', args)


def change_password(request, **kwargs):
	slug = request.user.userprofile.troop
	if request.method == 'POST':
		Passform = PasswordChangeForm(data=request.POST, user=request.user)

		if Passform.is_valid():
			Passform.save()
			update_session_auth_hash(request, Passform.user)
			return redirect('accounts:view_profile', slug=slug)
		else:
			return redirect("accounts:change_password", slug=slug)
	else:
		Passform = PasswordChangeForm(user=request.user)
		args = {'Passform': Passform, 'slug':slug}

		return render(request, 'accounts/change_password.html', args)		
#badges
def view_pioneer(request, **kwargs):
	slug = request.user.userprofile.troop
	args = {'user': request.user, 'slug_arg': slug,}
	return render(request, 'accounts/pioneer.html', args)

accounts/templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
    {% load staticfiles %}
    {% load static %}

{# JQuery #}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

		<!-- Bootstrap stuff -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    {# pace, loader #}
<script src="{% static 'pace/pace.js' %}"></script>
<link href="{% static 'pace/themes/white/pace-theme-flash.css' %}" rel="stylesheet" />


		<!-- Responsive meta tag -->
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% block extra_styles %}
    <style type="text/css">
      
      body{
        color: black;
        background-color: white;
        ;
      }

    </style>
    {% endblock %}
		{% block head %}
		<title>Base</title>
		{% endblock %}
	</head>
	{% block body-tag %}<body>{% endblock %}

{% block navbar %}

      {% if request.user.is_authenticated %}
  <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-info">
      <a class="navbar-brand mr-auto mr-lg-0" href="{% url 'accounts:home' slug=request.user.userprofile.troop %}">Scout Online Record Book</a>
 <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <div class="navbar-nav">
      {# class="nav-item nav-link active" href="{% url 'accounts:home' slug=request.user.userprofile.troop %}">Home span class="sr-only">(current) /span #}
{# class="nav-item nav-link" href="{% url 'accounts:view_profile' slug=request.user.userprofile.troop %}">Profile #}
      	<a class="nav-item nav-link" href="{% url 'accounts:logout' slug=request.user.userprofile.troop %}">Logout</a>
    </div>
</div>
    </nav>
 

      {% else %}
<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-info">
<a class="navbar-brand mr-auto mr-lg-0" href="# ">Scout Online Record Book</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
   <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <div class="navbar-nav"> 
<a class="nav-link" href="{% url 'login:login' %}">Login <span class="sr-only">(current)</span></a>
</div>
</div>
</nav>

      {% endif %}

</div>
</nav></body>
{% endblock %}
<br><br>
			{% block body %}
			{% endblock %}
<!-- {% block footer %}
<footer class="footer" style="background-color: ghostwhite">
      <div class="container-fluid">
        <span class="text-muted">A website for the ease of scouting.</span>
      </div>
    </footer>
    {% endblock %} -->



				<!-- jQuery first, then Tether, then Bootstrap JS. -->
				<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
				<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
				<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
	</body>
</html>

accounts/templates/bf_form.html
{% load widget_tweaks %}

{% for hidden_field in form.hidden_fields %}
	{{ hidden_field}}
{% endfor %}

{# non field errors #}
{% if form.non_field_errors %}
	<div class="alert alert-danger" role="alert">
		{% for error in form.non_field_errors %}
			{{  error.as_p }}
		{% endfor %}
	</div>
{% endif %}

{# actual form #}
{% for field in form.visible_fields %}
<div class="form-group">
	{{ field.label_tag }}

	{# bound = has data #} 
	{% if form.is_bound %}	}
		{% if field.errors %}
			{% render_field field class="form-control is-invalid" %}
			{% for error in field.errors %}
				<div class="invalid-feedback">
					{{ error.as_p }}
				</div>
			{% endfor %}
		{% else %}
			{# else = form is valid -- show a green box #}
			{% render_field field class="form-control is-valid" %}
		{% endif %}
	{% else %}
		{# else to if field is bound #}
		{% render_field field class="form-control" %}
	{% endif %}

{% if field.help_text %}
	<small class="form-text text-muted">
		{{ field.help_text.as_p }}
	</small>
	{% endif %}
</div>
{% endfor %}